import argparse
import logging
import sys
from pathlib import Path
from datetime import datetime
import bibtexparser

from lit_nwk.doi_resolver import NetworkConfig, CitationNetworkBuilder
from lit_nwk.aggregator import NetworkAggregator, DataExporter
from lit_nwk.visualizer import NetworkVisualizer

logger = logging.getLogger(__name__)


def main():
    parser = argparse.ArgumentParser(
        description="Citation Network Analysis Tool",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    parser.add_argument("dois", nargs="*", help="DOI identifiers (space-separated)")
    parser.add_argument(
        "--dois", dest="dois_arg", help="DOI identifiers (comma-separated)"
    )
    parser.add_argument(
        "-i", "--input", dest="input_file", help="Input file (.txt or .bib)"
    )

    parser.add_argument(
        "--run-name", type=str, help="Name of the run (used for output filenames)"
    )
    parser.add_argument(
        "--force-large-core", action="store_true", help="Disable the 50-paper safeguard"
    )

    parser.add_argument("--output-dir", default="./output", help="Output directory")
    parser.add_argument(
        "--min-year", type=int, default=2000, help="Min year (default: 2000)"
    )

    parser.add_argument(
        "--min-cocite-up", type=float, default=1.0, help="Min upstream score"
    )
    parser.add_argument(
        "--min-cocite-down", type=float, default=1.0, help="Min downstream score"
    )

    parser.add_argument(
        "--max-results", type=int, default=50, help="Max results per query"
    )
    parser.add_argument(
        "--recursive-threshold",
        type=float,
        default=0.25,
        help="Recursive threshold as fraction of core papers (default: 0.25)",
    )
    parser.add_argument("--max-iterations", type=int, default=5, help="Max iterations")

    parser.add_argument(
        "--peripheral-vote",
        type=float,
        default=0.5,
        help="Score generated by a peripheral connection (default: 0.5)",
    )
    parser.add_argument(
        "--penalty-factor",
        type=float,
        default=0.35,
        help="Asymptotic decay factor for the threshold gap to 100%% (default: 0.5)",
    )

    # [NEW] Multiplier for core importance inheritance
    parser.add_argument(
        "--core-award",
        type=float,
        default=0.1,
        help="Multiplier for extra points awarded to peripherals from connected cores (default: 0.1, range: 0-0.2)",
    )

    parser.add_argument("--csv", action="store_true", help="Generate CSV export")
    parser.add_argument("--json", action="store_true", help="Generate JSON export")
    parser.add_argument(
        "--no-report", action="store_true", help="Disable final operational report"
    )
    parser.add_argument(
        "--verbose", action="store_true", help="Print diagnostic logs to the terminal"
    )

    parser.add_argument("--no-cache", action="store_true", help="Disable API caching")

    parser.add_argument(
        "--network-filter",
        type=float,
        default=0.2,
        help="Network filter threshold multiplier (default 0.2)",
    )

    args = parser.parse_args()

    # [SAFEGUARD] Validate --core-award range
    if args.core_award < 0 or args.core_award > 0.2:
        print(
            f"❌ Error: --core-award must be between 0 and 0.2, got {args.core_award}"
        )
        sys.exit(1)

    log_level = logging.INFO if args.verbose else logging.WARNING
    logging.basicConfig(
        level=log_level, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    )

    # [UPDATED] Caching logic
    if not args.no_cache:
        try:
            import requests_cache

            requests_cache.install_cache("citation_debug_cache", expire_after=604800)
            logger.info("Local API cache is enabled.")
        except ImportError:
            logger.warning(
                "requests-cache is not installed. Running without cache. To enable, run: pip install requests-cache"
            )

    run_name = args.run_name or datetime.now().strftime("%Y%m%d_%H%M")

    dois = []
    if args.dois:
        dois.extend(args.dois)
    if args.dois_arg:
        dois.extend([d.strip() for d in args.dois_arg.split(",")])

    if args.input_file:
        file_path = Path(args.input_file)
        if not file_path.exists():
            print(f"❌ Error: Input file not found: {file_path}")
            sys.exit(1)

        if file_path.suffix.lower() == ".txt":
            with open(file_path, "r", encoding="utf-8") as f:
                dois.extend([line.strip() for line in f if line.strip()])
        elif file_path.suffix.lower() == ".bib":
            with open(file_path, "r", encoding="utf-8") as f:
                bib_database = bibtexparser.load(f)
                for entry in bib_database.entries:
                    if "doi" in entry:
                        clean_doi = (
                            entry["doi"]
                            .strip()
                            .replace("https://doi.org/", "")
                            .replace("http://dx.doi.org/", "")
                        )
                        dois.append(clean_doi)
        else:
            print("❌ Error: Unsupported file format. Use .txt or .bib")
            sys.exit(1)

    dois = list(dict.fromkeys(dois))

    if not dois:
        print("❌ Error: No DOIs provided.")
        parser.print_help()
        sys.exit(1)

    if len(dois) > 50 and not args.force_large_core:
        print(f"\n⚠️  SAFEGUARD TRIGGERED: You provided {len(dois)} initial DOIs.")
        print(
            "Running a network analysis with >50 seed papers can cause massive API throttling and result in an unreadable graph."
        )
        print(
            "If you are sure you want to proceed, run the command again with the --force-large-core flag.\n"
        )
        sys.exit(1)

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    config = NetworkConfig(
        min_year=args.min_year,
        min_cocitation_upstream=args.min_cocite_up,
        min_cocitation_downstream=args.min_cocite_down,
        max_results_per_query=args.max_results,
        recursive_expansion_threshold=args.recursive_threshold,
        max_iterations=args.max_iterations,
        run_name=run_name,
        peripheral_vote=args.peripheral_vote,
        penalty_factor=args.penalty_factor,
        core_award=args.core_award,
        network_filter=args.network_filter,
    )

    try:
        builder = CitationNetworkBuilder(config)
        aggregator = NetworkAggregator(config)

        publications, edges, all_scraped, seed_origins = (
            aggregator.build_network_recursive(dois, builder)
        )

        csv_path = output_dir / f"{run_name}_publications.csv"
        json_path = output_dir / f"{run_name}_network.json"
        html_path = output_dir / f"{run_name}_network.html"

        if args.csv:
            DataExporter.to_csv(all_scraped, str(csv_path), seed_origins)
        if args.json:
            DataExporter.to_json(publications, edges, str(json_path))

        initial_core = [
            doi
            for doi in publications
            if doi in seed_origins and seed_origins[doi] == "initial"
        ]
        secondary_core = [
            doi
            for doi in publications
            if doi in seed_origins and seed_origins[doi] != "initial"
        ]
        peripheral_nodes = [doi for doi in publications if doi not in seed_origins]

        # Populate HTML Sidebar Statistics
        run_stats = {
            "Run Name": run_name,
            "Total Graph Nodes": len(publications),
            "Initial Core Nodes": len(initial_core),
            "Secondary Core Nodes": len(secondary_core),
            "Peripheral Nodes": len(peripheral_nodes),
            "Total Graph Edges": len(edges),
            "Total Papers Scraped": len(all_scraped),
            "Max Results / Query": config.max_results_per_query,
            "Max Iterations": config.max_iterations,
            "Promotability Start Pct": f"{config.recursive_expansion_threshold * 100}%",
            "Peripheral Vote Base": config.peripheral_vote,
            "Core Award Multiplier": config.core_award,  # [NEW]
            "Iter Penalty Factor": config.penalty_factor,
            "Min Year Filter": config.min_year,
            # "Upstream Base Filter": config.min_cocitation_upstream,
            # "Downstream Base Filter": config.min_cocitation_downstream,
            "Caching": "Disabled" if args.no_cache else "Enabled",  # [NEW]
            "Network Filter Parameter": config.network_filter,
        }

        visualizer = NetworkVisualizer(publications, edges, seed_origins, run_stats)
        visualizer.generate_html(str(html_path))

        if not args.no_report:
            print("\n" + "=" * 70)
            print("CITATION NETWORK REPORT")
            print("=" * 70)
            print(f"Run Name                 : {run_name}")
            print(f"Max Results / Query      : {config.max_results_per_query}")
            print(f"Max Iterations           : {config.max_iterations}")
            print(
                f"Recursive Promotability  : Starts at {config.recursive_expansion_threshold * 100}% of current core"
            )
            print(f"Peripheral Vote Weight   : {config.peripheral_vote} points")
            print(
                f"Core Award Multiplier    : x{config.core_award} of connected core's score"
            )
            print(
                f"Iteration Penalty Factor : {config.penalty_factor} (Asymptotic curve closing the gap to 100%)"
            )
            print(f"Min Year Filter          : {config.min_year}")
            print(
                f"Peripheral Filter Base   : {config.min_cocitation_upstream} (Overrides to dynamic 10% final core)"
            )
            print("-" * 70)

            print(f"Graph Nodes (Total)      : {len(publications)}")
            print(f"  ↳ Initial Core Nodes   : {len(initial_core)}")
            print(f"  ↳ Secondary Core Nodes : {len(secondary_core)}")
            print(f"  ↳ Peripheral Nodes     : {len(peripheral_nodes)}")
            print(f"Graph Edges              : {len(edges)}")
            print(f"Total Papers Scraped     : {len(all_scraped)}")
            print("-" * 70)

            print(f"  INITIAL CORE DOIs ({len(initial_core)}):")
            for doi in initial_core:
                print(f"  - {doi}")

            print(f"\n  SECONDARY CORE PAPERS ADDED ({len(secondary_core)}):")
            if not secondary_core:
                print("  (None found meeting the threshold)")
            for doi in secondary_core:
                pub = publications[doi]
                print(
                    f"  - [{pub.doi}] {pub.title[:60]}... | {pub.authors[0] if pub.authors else 'Unknown'} | {pub.journal}"
                )

            if config.errors:
                print(f"\n   RETRIEVAL ERRORS ({len(config.errors)}):")
                for err in config.errors:
                    print(f"  - {err}")

            print("-" * 70)
            print(f"  Output Directory      : {output_dir.absolute()}")
            print(f"   ↳ Visualizer          : {html_path.name}")
            if args.csv:
                print(f"   ↳ CSV Export          : {csv_path.name}")
            print("=" * 70 + "\n")

    except Exception as e:
        logger.error(f"Error building network: {e}", exc_info=True)
        print(f"\n  A fatal error occurred: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
